# Generated by Django 5.1.2 on 2024-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
